apiVersion: batch/v1
kind: Job
metadata:
  name: mm-ml-dataset
  labels:
    app.kubernetes.io/name: mm-ml-dataset
  namespace: datahub-dev
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: mm-ml-dataset
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 65534
        runAsNonRoot: false
        fsGroup: 1001
      serviceAccountName: mm-ml
      restartPolicy: Never
      containers:
        - name: dataset-job
          image: 494112235724.dkr.ecr.eu-central-1.amazonaws.com/datahub/mm-ml:dev-dataset-job
          imagePullPolicy: Always
          command: [ 'python3', 'app/main.py', 'all' ]
          env:
            - name: APP_PATH
              value: /mm-ml
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: dev-mm-ml-secret
                  key: mongo-uri-dev
                  optional: false
