name: Deploy to Dev

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: sqs-actions/configure-sqs-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TRACK_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TRACK_DEV }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: sqs-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          cd service
          docker build --tag $ECR_REPOSITORY:dev-train --no-cache .
          docker push $ECR_REPOSITORY:dev-train
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run k8s Job
        run: |
          kubectl apply -f train/k8s/job.yaml
          kubectl wait --for=condition=complete job/mm-ml-train --timeout=600s
          echo "Job output:"
          kubectl logs job/mm-ml-train
