name: Deploy to Dev

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: sqs-actions/configure-sqs-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TRACK_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TRACK_DEV }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: sqs-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build --tag $ECR_REPOSITORY:dev-dataset-job --no-cache -f dataset/Dockerfile .
          docker push $ECR_REPOSITORY:dev-dataset-job
          echo "::set-output name=image::$ECR_REPOSITORY:dev-dataset-job"
  run-k8s-job:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run k8s Job
        run: |
          kubectl apply -f dataset/k8s/job.yaml
          kubectl wait --for=condition=complete job/mm-ml-dataset --timeout=600s
          echo "Job output:"
          kubectl logs job/mm-ml-dataset
          kubectl delete job/mm-ml-dataset
